definitions:
  steps: &steps
    - step: &base
        name: '(Dev) Webapp'
        runs-on: &base-runs-on
          - 'self.hosted'
          - 'linux'
          - 'ebspace'
        script: &base-code-deploy-pipe
          - pipe: atlassian/aws-code-deploy:0.2.10
            variables: &base-code-deploy-vars
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              COMMAND: 'upload'

pipelines:
  branches:
    dev:
      - step:
          name: '(Dev) Webapp'
          runs-on: *base-runs-on
          script:
            - apt install zip
            - mv cicd/dev/buildspec.yml .
            - zip -r ebspace-dev-webapp.zip .
            - <<: *base-code-deploy-pipe
              variables:
                <<: *base-code-deploy-vars
                APPLICATION_NAME: 'ebspace-dev'
                S3_BUCKET: 'ebspace-code-src/dev'
                ZIP_FILE: 'ebspace-dev-webapp.zip'
                VERSION_LABEL: 'ebspace-dev-webapp.zip'
      - step:
          name: '(Dev) Webapp-snyk'
          runs-on:
            - 'self.hosted'
            - 'macos'
            - 'snykebspace'
          script:
            - 
          artifcats:
            - 

    stage:
      - step:
          name: '(Stage) Webapp'
          runs-on: *base-runs-on
          script:
            - apt install zip
            - mv cicd/stage/buildspec.yml .
            - zip -r ebspace-stage-webapp.zip .
            - <<: *base-code-deploy-pipe
              variables:
                <<: *base-code-deploy-vars
                APPLICATION_NAME: 'ebspace-stage'
                S3_BUCKET: 'ebspace-code-src/stage'
                ZIP_FILE: 'ebspace-stage-webapp.zip'
                VERSION_LABEL: 'ebspace-stage-webapp.zip'
  tags:
    "**":
      - step:
          name: Call ZOOM API on New Tag
          runs-on:
            - 'self.hosted'
            - 'linux'
            - 'ebspace'
          script:
            - chmod +x sendmessage
            - ./sendmessage
            
  pull-requests:
    '**':  # For triggering the pipeline for all PRs
      - step:
          name: Run Trivy Scan
          runs-on:
            - 'self.hosted'
            - 'macos'
            - 'trivyebspace'
          script:
            - trivy fs --scanners config,secret,vuln . > trivy-report.json
          artifacts:
            - trivy-report.json

