#!/bin/bash
set -e

aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin <ecr-url>
cd /home/ebspace/dev/
docker-compose pull webapp_dev
docker-compose rm -s -f webapp_dev
docker-compose up -d webapp_dev
docker image prune -f
